### PR TITLE
Added SearchCharacter(string search) method

### PR DESCRIPTION
**Pull request by ahmed605**
Changes:

- Added SearchCharacter(string search) method to get an array of characters that match the search string and supports all types: Person, Object, Animal

- Added temporary GetCurrentQuestion() method (I mean by temporary that it will not be used mostly but it will be needed for some special cases)

### CODE REVIEW

**Comment by janniksam** [comment]
I will take care of this tommorow. 👍

**Comment by ahmed605** [comment]
any updates?

**Comment by janniksam** [comment]
Before merging, I would like to have atleast one (integration)test for the new SearchCharacter-method. Haven't had the time to one for it yet.

**Review by janniksam — APPROVED** [review]

**Comment by janniksam** [comment]
Merged and new version 0.2.1 published to nuget 👍

**Pull request merged**
