### PR TITLE
Added GetHallOfFame() method to fetch Hall of fame list from Akinator

### PR DESCRIPTION
**Pull request by ahmed605**
Changes:

- Added GetHallOfFame() method to fetch Hall of fame list from Akinator :
- Currently supports English, German, French, Arabic languages only

### CODE REVIEW

**Comment by janniksam** [comment]
I did chance some stuff to meet my coding standards. Also I created a new model instead of giving back the external model directly.

**Comment by ahmed605** [comment]
Good, but why? I think the result is almost the same but it's now more bigger (a lot of code lines)

**Comment by janniksam** [comment]
Exposing the actual Akinator layer I get from Akinator to the outside world is a simpler approach, but imho it is alot cleaner to implement another layer.

Whenever Akinator changes it's json / xml data, we just have to remap it to our projection-classes. We have to fix everything internally, but basically our consumers will not have to change anything. The risk of having breaking changes is slightly lower.

**Comment by ahmed605** [comment]
Oh now I understood, You are a great developer BTW!

**Review by janniksam — APPROVED** [review]

**Pull request merged**
