### PR TITLE
Automatic Server Location

### LINKED ISSUE #11: Automatic server and server type finder

### LINKED ISSUE #12: Randomize server in case there are multiple
Possibility to randomize the server type. Instead of selecting a specific type (animal, person, object)

### PR DESCRIPTION
**Pull request by janniksam**
Closes #11 & closes #12

### CODE REVIEW

**Comment by ahmed605** [comment]
I'm getting `A connection attempt failed because the connected party did not properly respond after a period of time` using that, this is strange, I will try running UWP tests instead

**Comment by ahmed605** [comment]
hmm... I'm getting that error also with UWP tests, @janniksam any suggestions?

**Comment by janniksam** [comment]
> 
> 
> I'm getting `A connection attempt failed because the connected party did not properly respond after a period of time` using that, this is strange, I will try running UWP tests instead

I need some more infos. A callstack or something, so I can see, where exactly the exception is thrown.

**Comment by ahmed605** [comment]
@janniksam the error happened when calling GetAsync() in HttpClient in AkiWebClient, 90% it's NOT your fault, .Net Core is famous with this type of errors

**Comment by janniksam** [comment]
One thing, I will have to improve is the server "health checks". They are all done at the retrieval. I will add some lazy loading later. ;)

**Comment by ahmed605** [comment]
@janniksam so do you have any suggestions to fix that error?

**Comment by ahmed605** [comment]
@janniksam I have fixed the problem, the problem was that my internet provider changed my DNS servers into a very bad DNS servers without informing me even MS Docs wasn't reachable and sometimes GH too

**Review by ahmed605 — APPROVED** [review]
Great work!

**Comment by janniksam** [comment]
not done yet :)

**Comment by janniksam** [comment]
@ahmed605 I optimized the caching. It should be alot faster now, because the health checks are now performed lazy, which means that they are only done when actually needed (instead of always checking every server on first search).

**Comment by janniksam** [comment]
@ahmed605 Would be awesome, if you could verify in the next couple of day, that it's still working on your end. Took me some time, went a few wrong paths at first.

**Comment by ahmed605** [comment]
@janniksam 
Results#1

**Pull request merged**
