### PR TITLE
Added Arabic, Italian, Spanish and Russian languages

### PR DESCRIPTION
**Pull request by ahmed605**
Added:

- Arabic person server

- Italian person server

- Spanish person server

- Russian person server

### CODE REVIEW

**Comment by janniksam** [comment]
Looking good to me. Would you mind duplicating the test "SimpleWorkflowTest" and making a variant for each new language you've added?

The reason would be to have a fast way of testing, that each languages servers are still working.

**Comment by ahmed605** [comment]
I will write the servers status language by language

**Comment by ahmed605** [comment]
Arabic server works ✔

**Comment by ahmed605** [comment]
Italian server works ✔

**Comment by ahmed605** [comment]
Russian server works ✔

**Comment by ahmed605** [comment]
Spanish server works ✔

So all new severs works ✔✔✔✔

The fastest server in that new server is Spanish server because it's not mostly used by Akinator

**Comment by janniksam** [comment]
Ofcourse I believe you, but I'd like to have some additional Integration tests for each server. Please copy and paste the test "public async Task SimpleWorkflowTest()" for each new server and change it to use your new servers, so when I run the tests in 1 or 2 months, I get some instant feedback if the API and alle servers are still working.

**Comment by ahmed605** [comment]
That what I did I tried playing with all new servers and it works

**Comment by janniksam** [comment]
I added the test for each configuration by myself now.

**Comment by ahmed605** [comment]
Oh now I understood what you said before I'm sorry for the misunderstanding!

**Pull request merged**
