### PR TITLE
Added UndoAnswer() Method

### PR DESCRIPTION
**Pull request by ahmed605**
Changes:

- Added UndoAnswer() Method

### CODE REVIEW

**Review by janniksam — APPROVED** [review]

**Comment by janniksam** [comment]
I had to revert your changes.

**Comment by janniksam** [comment]
Some of the changes rolled back the changes of your previous pull request

**Comment by janniksam** [comment]
I will manually add the changes from this pull request now.

**Comment by janniksam** [comment]
fcda87b0a7f1246a5145f8e1e609991299892b6e

**Comment by ahmed605** [comment]
@janniksam could you add me as a collaborator to this repo to easily add new changes and features to a dev branch? and you can review the changes later and merge it to master

**Pull request merged**
